#!/bin/bash

FILES=`find . -name '*.py' ! -name '*_test.py' ! -name '__init__.py' ! -name 'fixpath.py' ! -name 'run_all_tests.py' ! -name 'AT*.py'`
if [ -z "$FILES" ]
then
    exit 1
fi
# echo $FILES

print $@

pylint --rcfile=pylintrc $@ $FILES

